"""Convert the raw Delhi Metro CSV into js/metro-data.js.

Source: Kaggle "Delhi Metro Dataset" (station name, line, distance from first
station, latitude, longitude) as mirrored on GitHub. Station names carry notes
like "[Conn: Blue]" which are stripped so interchanges share one name.
"""
import csv, json, re
from collections import defaultdict

LINES = {
    "Red line": ("Red Line", "#e2231a"),
    "Yellow line": ("Yellow Line", "#f2c200"),
    "Blue line": ("Blue Line", "#1565c0"),
    "Blue line branch": ("Blue Line Branch", "#4f8fd6"),
    "Green line": ("Green Line", "#00a650"),
    "Green line branch": ("Green Line Branch", "#4cc27f"),
    "Voilet line": ("Violet Line", "#7f3f98"),
    "Magenta line": ("Magenta Line", "#b5006a"),
    "Pink line": ("Pink Line", "#ec6fa8"),
    "Aqua line": ("Aqua Line", "#00a7b5"),
    "Orange line": ("Airport Express", "#f58220"),
    "Gray line": ("Grey Line", "#8a8f98"),
    "Rapid Metro": ("Rapid Metro Gurugram", "#2f9fd8"),
}
# Interchanges that the raw file stores under different names (walkway links)
WALKWAYS = [
    ("Dhaula Kuan", "Durgabai Deshmukh South Campus"),
    ("New Delhi", "New Delhi-Airport Express"),
    ("Noida Sector 52", "Noida Sector 51"),
    ("Punjabi Bagh", "Punjabi Bagh West"),
]
# A few stations in the source file carry wrong coordinates; approximate fixes
COORD_FIX = {
    "Noida Sector 101": (28.5615, 77.3870),
    "Alpha 1 Greater Noida": (28.4712, 77.5180),
    "Delta 1 Greater Noida": (28.4795, 77.5255),
    "GNIDA Office": (28.4850, 77.5330),
    "Depot Greater Noida": (28.4915, 77.5405),
}
RENAME = {"Huda City Centre": "Millennium City Centre Gurugram", "Netaji Subash Place": "Netaji Subhash Place",
          "Bahdurgarh City": "Bahadurgarh City"}


def norm(n):
    n = re.sub(r"\[.*?\]", "", n)
    n = re.sub(r"\(.*?\)", "", n)
    n = re.sub(r"Conn\s*:\s*\w+", "", n)
    n = re.sub(r"\s+", " ", n).strip()
    return RENAME.get(n, n)


rows = list(csv.DictReader(open("data/delhi_metro_raw.csv", encoding="utf-8", errors="replace")))
stations, lines = {}, defaultdict(list)
for r in rows:
    name = norm(r["Station Names"])
    lat, lon = COORD_FIX.get(name, (float(r["Latitude"]), float(r["Longitude"])))
    if name not in stations:
        stations[name] = {"name": name, "lat": round(lat, 6), "lon": round(lon, 6), "layout": r["Layout"].strip(),
                          "opened": r["Opened(Year)"].strip()}
    lines[r["Metro Line"]].append((float(r["Dist. From First Station(km)"]), name))

names = sorted(stations)
idx = {n: i for i, n in enumerate(names)}
out_lines = []
for key, seq in lines.items():
    seq.sort()
    label, color = LINES[key]
    out_lines.append({"name": label, "color": color, "express": key == "Orange line",
                      "stops": [[idx[n], round(d, 2)] for d, n in seq]})
order = [v[0] for v in LINES.values()]
out_lines.sort(key=lambda l: order.index(l["name"]))
walk = [[idx[a], idx[b]] for a, b in WALKWAYS if a in idx and b in idx]
data = {"stations": [stations[n] for n in names], "lines": out_lines, "walkways": walk}
with open("js/metro-data.js", "w", encoding="utf-8") as f:
    f.write("// Generated by tools/build_data.py — Delhi Metro stations, lines and interchanges\n")
    f.write("const METRO = " + json.dumps(data, separators=(",", ":"), ensure_ascii=False) + ";\n")
print(len(names), "stations", len(out_lines), "lines", len(walk), "walkways")
